services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0 # najnowsza wersja 
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:9.0.0
    container_name: logstash
    ports:
      - "5020:5020"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  go-app:
    build: .
    container_name: go-app
    depends_on:
      - logstash
    environment:
      - LOGSTASH_HOST=logstash:5020

volumes:
  esdata:
